services:
  - type: web
    runtime: image
    name: skywatch-api
    region: frankfurt
    plan: free
    image:
      url: ghcr.io/harisbeg26/opensky-iis-projekt:api-latest
      creds:
        fromRegistryCreds:
          name: github-container-registry
    healthCheckPath: /api/health
    envVars:
      - key: ALLOW_LOCAL_MODEL_FALLBACK
        value: "true"
      - key: HF_INFERENCE_ENABLED
        value: "false"
