name: Fetch data on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  fetch_opensky:
    name: Fetch and pre-process OpenSky data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN || github.token }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: DVC setup remote
        env:
          DAGSHUB_S3_ENDPOINT_URL: ${{ vars.DAGSHUB_S3_ENDPOINT_URL }}
          DAGSHUB_ACCESS_KEY_ID: ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          DAGSHUB_SECRET_ACCESS_KEY: ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}
        run: |
          if [ -n "$DAGSHUB_S3_ENDPOINT_URL" ]; then
            uv run dvc remote add -d origin s3://dvc --force
            uv run dvc remote modify origin endpointurl "$DAGSHUB_S3_ENDPOINT_URL"
            uv run dvc remote modify origin --local access_key_id "$DAGSHUB_ACCESS_KEY_ID"
            uv run dvc remote modify origin --local secret_access_key "$DAGSHUB_SECRET_ACCESS_KEY"
          else
            echo "DAGSHUB_S3_ENDPOINT_URL is not set. Skipping remote setup."
          fi

      - name: Run DVC pipeline
        env:
          OPENSKY_USERNAME: ${{ secrets.OPENSKY_USERNAME }}
          OPENSKY_PASSWORD: ${{ secrets.OPENSKY_PASSWORD }}
          OPENSKY_URL: ${{ vars.OPENSKY_URL }}
          DAGSHUB_S3_ENDPOINT_URL: ${{ vars.DAGSHUB_S3_ENDPOINT_URL }}
          DAGSHUB_ACCESS_KEY_ID: ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          DAGSHUB_SECRET_ACCESS_KEY: ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}
        run: |
          uv run dvc pull
          uv run dvc status
          uv run dvc repro
          uv run dvc push
          git add dvc.lock
          git commit -m "Update dvc.lock on `date` with GitHub Actions" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
